# Generated by Django 3.2.25 on 2025-06-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Achaba Analytics', max_length=255),
        ),
    ]
