# Generated by Django 3.2.25 on 2025-06-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_website', '0012_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Read More from the above Link', max_length=255),
        ),
    ]
