# Generated by Django 3.2.25 on 2025-06-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_website', '0013_alter_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='', max_length=255),
        ),
    ]
